spring:
  application:
    name: weightlifting-protocol-backend
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true
  datasource:
    name: sqlite
    url: jdbc:sqlite:wlprotocol.db
    driver-class-name: org.sqlite.JDBC
#logging:
#  level:
#    org.springdoc.core.utils.SpringDocAnnotationsUtils: ERROR