spring:
  application:
    name: weightlifting-protocol-backend
  datasource:
    name: datasource
    url: jdbc:postgresql://localhost:5432/wl_protocol?autoReconnect=true&useSSL=false
    username: postgres
    password: postgres
